### ISSUE TITLE
missing entries

### ISSUE THREAD

**Issue by dragosperca** [MathieuTurcotte/go-trie#2]
loading from a large 610000 words dictionary and then shuffling around some 25000 items, the search in trie fails constantly to find items, even if those items are definitely supposed to be there.

To test this: https://gist.github.com/dragosperca/2d5e2f04816c639c4e7d

Is the trie build process that fails or the search itself?

**Comment by MathieuTurcotte** [comment]
The words have to be sorted, are they?

**Comment by dragosperca** [comment]
yes, if you look within the gist, there's a dropbox link to download the words.txt file
words are sorted
it's only then they are shuffled to emulate some sort of randomness in the search

**Comment by MathieuTurcotte** [comment]
Is it failing on all entries or only a subset?

**Comment by dragosperca** [comment]
constantly failing on the same subset.

What I did was shuffle the entire dictionary and then search the whole trie again. Using the gist provided shows random results because of the slice

some printscreens:

https://www.dropbox.com/s/nt56seatmoncujr/SnappyApp%20SnappyApp%2C%20Today%20at%2015.00.17.png?dl=0

https://www.dropbox.com/s/ozzl6vl5bkl99tq/console.png?dl=0

**Comment by MathieuTurcotte** [comment]
Yeah, looks like there's some bug. II can't reproduce with my own dictionaries but definitely can with yours. I'll take a look next weekend.

**Comment by dragosperca** [comment]
thank you, much appreciated

**Comment by MathieuTurcotte** [comment]
It's actually an impressive one. The encoding of the equivalence class is incorrect. I shouldn't be doing string(t.Child.id) but instead strconv.Itoa(int(t.Child.id)) since I don't want to interpret the ID as a rune. This is causing some nodes with different equivalence classes to collide. It doesn't reproduce with most dictionaries, but it does with yours. You actually need a pretty big one or a very carefully crafted test.

**Comment by dragosperca** [comment]
fantastic, thanks Mathieu, it works very well now!
